version: '3.8'

services:
  telmi-app:
    build: .
    container_name: telmi-streamlit
    ports:
      - "8501:8501"
    environment:
      - CLICKHOUSE_HOST=172.20.157.162
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_DATABASE=Default
      - CLICKHOUSE_USERNAME=default
      - CLICKHOUSE_PASSWORD=
      - APP_URL=/clickhouseagent/
      - DEBUG=false
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./exports:/app/exports
      - ./visualizations:/app/visualizations
    restart: unless-stopped
    networks:
      - telmi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  telmi-network:
    driver: bridge

volumes:
  telmi-data:
    driver: local