[global]
developmentMode = false

[server]
headless = true
port = 3001
address = "0.0.0.0"
baseUrlPath = "/clickhouseagent"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
showErrorDetails = false

[theme]
primaryColor = "#4299e1"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7fafc"
textColor = "#1a202c"
font = "sans serif"

[client]
caching = true
displayEnabled = true
showErrorDetails = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true